Add script for downloading triage logs
openshift-assisted/assisted-scripts pull request #5
Opened 2022-06-02 15:52 UTC by empovit

2022-06-02 15:57 UTC, javipolo approved these changes

2022-06-02 16:43 UTC, osherdp requested changes
Maybe just change dirs hierarchy, because it's a bit redundant to have ``assisted-scripts/triage/triage-scripts/``
Something like ``triage/triage-scripts/ -> triage/logs-gathering/``

2022-06-02 16:43 UTC, osherdp commented on triage/triage-scripts/download-logs.py
> +# and subdirectories. The files/directories will be recursively downloaded into "2022-03-30_20-14-19_fab47716-04e6-401b-8b89-e414d030a298".
```suggestion
"""
This script takes a URL of a directory in the NGINX-file browser format (https://github.com/mohamnag/nginx-file-browser),
and downloads its contents into a subdirectory inside the working directory. A name of the destination directory can be
either given as the second argument (after the URL), or will be derived from the last part of the URL. Files in the known
archive formats will be unpacked. The subdirectory will be relative to the working directory.

Example: http://logs.example.com/#/2022-03-30_20:14:19_fab47716-04e6-401b-8b89-e414d030a298/ will be converted into
http://logs.example.com/files/2022-03-30_20:14:19_fab47716-04e6-401b-8b89-e414d030a298/, which returns a JSON list of files
and subdirectories. The files/directories will be recursively downloaded into "2022-03-30_20-14-19_fab47716-04e6-401b-8b89-e414d030a298".
"""
```

2022-06-02 16:44 UTC, osherdp commented on triage/triage-scripts/download-logs.py
> +    r = requests.get(base_url, stream=True)
otherwise you might download content of 4xx/5xx page without knowing it

2022-06-02 16:49 UTC, javipolo commented
> Maybe just change dirs hierarchy, because it's a bit redundant to have `assisted-scripts/triage/triage-scripts/` Something like `triage/triage-scripts/ -> triage/logs-gathering/`

I would make a catch-all directory for those small scripts, like assisted-scripts/triage/scripts or something like that

I doubt there will be much log-gathering extra things, and having a directory per script seems a little bit too much

2022-06-02 16:53 UTC, osherdp commented
> > Maybe just change dirs hierarchy, because it's a bit redundant to have `assisted-scripts/triage/triage-scripts/` Something like `triage/triage-scripts/ -> triage/logs-gathering/`
> 
> I would make a catch-all directory for those small scripts, like assisted-scripts/triage/scripts or something like that
> 
> I doubt there will be much log-gathering extra things, and having a directory per script seems a little bit too much

So in this case just putting the new script directly under triage/. This whole repo is scripts, so no need to remind of this content in any subdirectory 😄

2022-06-02 18:54 UTC, empovit commented
PTAL

2022-06-06 07:13 UTC, osherdp approved these changes

2022-06-06 07:13 UTC, merged